version: '3'
services:
  ssh-tunnel:
    build:
      context: ./
      args:
        PYTHON_VER: 3.6
        proxy: ${http_proxy}
    volumes:
            - ./src:/src
            - ./config:/config
            - ./key:/key
    restart: always
  nginx-proxy:
    image: nginx
    volumes:
      - ./config/nginx-proxy.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.211.0.0/16

